backup_dir: C:/Users/danie/Desktop
encrypt_password: ''
retention_days: 3
sftp:
  host: test.rebex.net
  password: password
  port: 22
  remote_dir: /pub/example
  username: demo
source_dir: D:/0.3 Documenti/Curriculum/IT
